---
platform: linux

image_resource:
  type: registry-image
  source: {repository: cirocosta/builder}

params:
  REPOSITORY: cirocosta/flight_recorder
  TAG: latest
  CONTEXT: repository
  TARGET: ""

inputs:
- name: repository

outputs:
- name: image

run: {path: build}
