image:
  repository: cirocosta/flight_recorder
  tag: latest
  pullPolicy: Always

affinity: {}

fullnameOverride: ""

nameOverride: ""

nodeSelector: {}

replicaCount: 1

resources: {}

tolerations: []

service:
  type: ClusterIP
  port: 80
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"

secrets:
  postgresUser:
  postgresPassword:
  postgresCaCert:
  postgresClientCert:
  postgresClientKey:

secretsPath: /var/run/postgres-secrets

flight_recorder:
  postgres:
    host:
    port:
    socket:
    sslmode: disable
    connectTimeout:
    database:

