apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flight_recorder.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "flight_recorder.name" . }}
    helm.sh/chart: {{ include "flight_recorder.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  postgresql-user: {{ required "postgres user must be supplied" .Values.secrets.postgresUser | b64enc | quote }}
  postgresql-password: {{ required "postgres user must be supplied" .Values.secrets.postgresPassword | b64enc | quote }}
  postgresql-ca-cert: {{ default "" .Values.secrets.postgresCaCert | b64enc | quote }}
  postgresql-client-cert: {{ default "" .Values.secrets.postgresClientCert | b64enc | quote }}
  postgresql-client-key: {{ default "" .Values.secrets.postgresClientKey | b64enc | quote }}
